language: java
jdk:
  - openjdk8
branches:
  only:
    - master
before_install:
  - chmod +x gradlew

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.gradle"
script: "./gradlew clean build --stacktrace"

before_deploy:
  - zip -r multimodule *
  - mkdir -p multi
  - mv multimodule.zip multi/multimodule.zip
deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    bucket: springboot-multimodule-test-bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: multi
    wait-until-deployed: true
    on:
      repo: pds0309/mul2
      branch: master

notifications:
  email:
    recipients:
      - ehd0309@naver.com
